# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keynest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='keynest_id',
            field=models.IntegerField(unique=True),
        ),
    ]
