# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keynest', '0003_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='key',
        ),
        migrations.AddField(
            model_name='key',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='keynest.Store'),
            preserve_default=False,
        ),
    ]
