# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keynest', '0004_auto_20190528_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keynest.Store'),
        ),
    ]
