# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keynest', '0005_auto_20190528_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='property_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
