# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keynest', '0006_store_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='property_id',
        ),
        migrations.AddField(
            model_name='key',
            name='property_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
