# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keynest', '0007_auto_20190529_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='full_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
