# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keynest', '0010_auto_20190529_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='full_status',
        ),
        migrations.RemoveField(
            model_name='key',
            name='store',
        ),
        migrations.AddField(
            model_name='key',
            name='store_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='store_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='store_time',
            field=models.TextField(null=True),
        ),
    ]
